### ISSUE TITLE
"Permission denied @ dir_s_mkdir - /orphan_lists" while "bundle exec rake db:setup"

### ISSUE THREAD

**Issue by futurus** [AgileVentures/osra#453]
I'm trying to set up osra in my c9 space. Ran into 
```
Errno::EACCES: Permission denied @ dir_s_mkdir - /orphan_lists
/usr/local/rvm/gems/ruby-2.2.0/gems/paperclip-5.1.0/lib/paperclip/storage/filesystem.rb:39:in `block in flush_writes'
/usr/local/rvm/gems/ruby-2.2.0/gems/paperclip-5.1.0/lib/paperclip/storage/filesystem.rb:37:in `each'
/usr/local/rvm/gems/ruby-2.2.0/gems/paperclip-5.1.0/lib/paperclip/storage/filesystem.rb:37:in `flush_writes'
/usr/local/rvm/gems/ruby-2.2.0/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:244:in `save'
...
```
Looked at filesystem.rb:39, I tried printing out the path and got "/orphan_lists/spreadsheets/000/000/001/original". This looks like an absolute path? Could I have done something wrong earlier?

**Comment by NikitaAvvakumov** [comment]
@futurus I just changed the Paperclip config to use the public/system subfolder in dev and test envs, this should take care of it

**Comment by futurus** [comment]
Working now. Thanks!
